### PR TITLE
Bubble_sort

### PR DESCRIPTION
**Pull request by rahalrazika**
- add rubocop
- add the ruby  gem 
- add the ruby file

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @rahalrazika and @Abidoyinsola1, great job with this project :smile: Let us kindly address a few comments and get our project approved :+1: Kindly find comments below:
- Let us configure Github actions correctly, currently, it is not checking for errors
- Let us create a new file for `bubble_sort_by` or `bubble_sort` method

Kindly fix these and submit another code review :slightly_smiling_face: 
_Happy coding_ :woman_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
# Changes required 🔧 

It works, but you have to do a bit of cleansing before continuing.

1. Remove any statements that print to STDOUT (like puts)

2. Place your `bubble_sort_by` method inside of your `buble_sort.rb` file

Also, for your next projects make sure your PR (Pull Request) has a meaningful title and a useful summary, that's the first thing code reviewers see, and you should try to make them look professional.

## What to do now?

After implementing the changes please submit another CRR (Code Review Request).

You can find me in slack as **srodrig**, happy coding!

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
# Project Approved :thumbsup:
## Hello Team,  You have done a great job with this project. :clap:
### check comment below
#### You can go ahead and merge !!!

**Review by kobiyoyo — APPROVED** [review]
Approved

**Pull request merged**
